TRUNCATE updates;
TRUNCATE stocks;
TRUNCATE cryptocurrencies;
TRUNCATE commodities;

TRUNCATE news;

TRUNCATE transactions;
TRUNCATE funds;

INSERT INTO stocks (name, ovalue, sector, description) VALUES
("Apple", 157.5, "Technology", "The Company designs, manufactures and markets mobile communication and media devices, personal computers and portable digital music players, and sells a variety of related software, services, accessories, networking solutions and third-party digital content and applications. The Company's products and services include iPhone, iPad, Mac, iPod, Apple Watch, Apple TV, a portfolio of consumer and professional software applications, iOS, OS X and watchOS operating systems, iCloud, Apple Pay and a variety of accessory, service and support offerings. "),
("General Motors", 34.83, "Automotive", "General Motors Company, commonly known as GM, is an American multinational corporation headquartered in Detroit, Michigan, that designs, manufactures, markets, and distributes vehicles and vehicle parts, and sells financial services. With global headquarters at the Renaissance Center in Detroit, Michigan, United States, GM manufactures cars and trucks in 35 countries. In 2008, 8.35 million. GM cars and trucks were sold globally under various brands. 10 million cars sold milestone was exceeded on 2016. Current auto brands are Buick, Cadillac, Chevrolet, GMC, Holden, and Wuling. Former GM automotive brands include McLaughlin, Oakland, Oldsmobile, Pontiac, Hummer, Saab, Saturn, as well as Vauxhall, and Opel, which were bought by Groupe PSA in 2017. "),
("Microsoft", 72.49, "Technology", "Microsoft Corporation  is an American multinational technology company with headquarters in Redmond, Washington. It develops, manufactures, licenses, supports and sells computer software, consumer electronics, personal computers, and services. Its best known software products are the Microsoft Windows line of operating systems, the Microsoft Office suite, and the Internet Explorer and Edge web browsers. Its flagship hardware products are the Xbox video game consoles and the Microsoft Surface tablet lineup. As of 2016, it is the world's largest software maker by revenue, and one of the world's most valuable companies. The word Microsoft is a portmanteau of microcomputer and software. "),
("Tesla", 347.46, "Automotive", "Tesla, Inc. is an American automaker, energy storage company, and solar panel manufacturer based in Palo Alto, California. Founded in 2003, the company specializes in electric cars, lithium-ion battery energy storage, and, through their SolarCity subsidiary, residential solar panels. "),
("Amazon", 956.00, "E-Commerce", "Amazon.com, Inc. is an American electronic commerce and cloud computing company based in Seattle, Washington that was founded on July 5, 1994 by Jeff Bezos. The tech giant is the largest Internet-based retailer in the world by total sales and market capitalization. Amazon.com started as an online bookstore and later diversified to sell DVDs, Blu-rays, CDs, video downloads/streaming, MP3 downloads/streaming, audiobook downloads/streaming, software, video games, electronics, apparel, furniture, food, toys, and jewelry. The company also produces consumer electronics - notably, Kindle e-readers, Fire tablets, Fire TV, and Echo - and is the world's largest provider of cloud infrastructure services. Amazon also sells certain low-end products like USB cables under its in-house brand AmazonBasics. "),
("Netflix", 166.6, "Entertainment", "Netflix is an American entertainment company founded by Reed Hastings and Marc Randolph on August 29, 1997, in Scotts Valley, California. It specializes in and provides streaming media and video-on-demand online and DVD by mail. In 2013, Netflix expanded into film and television production, as well as online distribution. As of 2017, the company has its headquarters in Los Gatos, California. "),
("Facebook", 167.41, "Technology", "Facebook is an American for-profit corporation and an online social media and social networking service based in Menlo Park, California. The Facebook website was launched on February 4, 2004, by Mark Zuckerberg, along with fellow Harvard College students and roommates, Eduardo Saverin, Andrew McCollum, Dustin Moskovitz, and Chris Hughes. "),
("Starbucks", 52.7, "Fast Moving Consumer Goods", "Starbucks Corporation is an American coffee company and coffeehouse chain. Starbucks was founded in Seattle, Washington in 1971. As of November 2016, it operates 23,768 locations worldwide. "),
("Johnson and Johnson", 132.63, "Fast Moving Consumer Goods", "Johnson & Johnson is an American multinational medical devices, pharmaceutical and consumer packaged goods manufacturing company founded in 1886. Its common stock is a component of the Dow Jones Industrial Average and the company is listed among the Fortune 500. "),
("JP Morgan", 90.74, "Finance", "JPMorgan Chase & Co. is a U.S. multinational banking and financial services holding company headquartered in New York City. It is the largest bank in the United States, the world's third largest bank by total assets, with total assets of roughly US$2.5 trillion, and the world's most valuable bank by market capitalization, topping ICBC. It is a major provider of financial services, and according to Forbes magazine is the world's sixth largest public company based upon a composite ranking. The hedge fund unit of JPMorgan Chase is the second largest hedge fund in the United States. The company was formed in 2000, when Chase Manhattan Corporation merged with J.P. Morgan & Co. "),
("Walmart", 79.69, "Retail", "Wal-Mart Stores, Inc. is an American multinational retailing corporation that operates as a chain of hypermarkets, discount department stores, and grocery stores. Headquartered in Bentonville, Arkansas, the company was founded by Sam Walton in 1962 and incorporated on October 31, 1969. As of January 31, 2017, Walmart has 11,695 stores and clubs in 28 countries, under a total of 63 banners. The company operates under the name Walmart in the United States and Canada. It operates as Walmart de Mexico y Centroamerica in Mexico and Central America, as Asda in the United Kingdom, as the Seiyu Group in Japan, and as Best Price in India. It has wholly owned operations in Argentina, Chile, Brazil, and Canada. It also owns and operates the Sam's Club retail warehouses. "),
("Alibaba", 167.5, "E-Commerce", "Alibaba Group Holding Limited is a Chinese e-commerce company that provides consumer-to-consumer, business-to-consumer and business-to-business sales services via web portals. It also provides electronic payment services, a shopping search engine and data-centric cloud computing services. The group began in 1999 when Jack Ma founded the website Alibaba.com, a business-to-business portal to connect Chinese manufacturers with overseas buyers. In 2012, two of Alibaba's portals handled 1.1 trillion yuan ($170 billion) in sales. Suppliers from other countries are supported (with more stringent checks than for Chinese companies), but the company primarily operates in the People's Republic of China (PRC). At closing time on the date of its initial public offering(IPO), 19 September 2014, Alibaba's market value was US$231 billion. However, the stock has traded down and market cap was about $212 billion at the end of December 2015."),
("Caterpillar", 113.92, "Diversified", "Caterpillar, Inc. engages in the manufacture of construction and mining equipment, diesel and natural gas engines, industrial gas turbines, and diesel-electric locomotives. It provides technology for construction, transportation, mining, forestry, energy, logistics, electronics, financing, and electric power generation. It operates through the following segments: Construction Industries, Resource Industries, Energy & Transportation, and Financial Products. The Construction Industries segment supports customers using machinery in infrastructure and building construction applications. The Resource Industries segment responsible for supporting customers using machinery in mining and quarrying applications and it includes business strategy, product design, product management, and development, manufacturing, marketing and sales and product support. The Energy & Transportation segment supports customers in oil and gas, power generation, marine, rail, and industrial applications. The Financial Products segment line business provides a wide range of financing alternatives to customers and dealers for Caterpillar machinery and engines, solar gas turbines as well as other equipment and marine vessels. The company was founded on April 15, 1925 and is headquartered in Peoria, IL."),
("Coca-Cola", 45.67, "Fast Moving Consumer Goods", "The Coca-Cola Company, incorporated on September 5, 1919, is a beverage company. The Company owns or licenses and markets non-alcoholic beverage brands, primarily sparkling beverages and a range of still beverages, such as waters, flavoured waters and enhanced waters, juices and juice drinks, ready-to-drink teas and coffees, sports drinks, dairy and energy drinks. The Company's segments include Europe, Middle East and Africa; Latin America; North America; Asia Pacific; Bottling Investments, and Corporate. The Company owns and markets a range of non-alcoholic sparkling beverage brands, including Coca-Cola, Diet Coke, Fanta and Sprite. As of December 31, 2016, the Company owned or licensed and marketed over 500 non-alcoholic beverage brands. The Company markets, manufactures and sells beverage concentrates, which are referred to as beverage bases, and syrups, including fountain syrups (concentrate business or concentrate operations), and finished sparkling and still beverages (finished product business or finished product operations). The Company makes its beverage products available to consumers across the world through its network of Company-owned or -controlled bottling and distribution operations, as well as bottling partners, distributors, wholesalers and retailers."),
("American Express", 85.31, "Finance", "American Express Co. operates as a global services company, which engages in the provision of credit card, financial, and global travel services. It operates through the following business segments: U.S. Card Services, International Card Services, Global Commercial Services, Global Network & Merchant Services, and Corporate & Other. The USCS segment offers products and services to consumers and small businesses in the United States and provides travel services to card members and other customers. The ICS segment provides proprietary consumer and small business cards outside the United States. The GCS segment includes global corporate payment services to large and mid-sized companies. The GNMS segment operates a global payments network that processes and settles proprietary and non-proprietary card transactions. It also provides point-of-sale products, multi-channel marketing programs and capabilities, services and data, leveraging the global closed-loop network. The Corporate & Other segment includes corporate functions and certain other businesses including the company's enterprise growth business and other company operations. The company was founded by Henry Wells, William G. Fargo and John Warren Butterfield on March 28, 1850 and is headquartered in New York, NY.");

UPDATE stocks SET current = ovalue, pclose = ovalue;
UPDATE stocks SET difference = ovalue - pclose, percentage = (((ovalue - pclose) * 100) / pclose);

INSERT INTO cryptocurrencies (name, ovalue, description) VALUES
("Bitcoin", 4090.01, "Bitcoin is a worldwide cryptocurrency and digital payment system invented by an unknown programmer, or a group of programmers, under the name Satoshi Nakamoto. It was released as open-source software in 2009. The system is peer-to-peer, and transactions take place between users directly, without an intermediary. These transactions are verified by network nodes and recorded in a public distributed ledger called a blockchain. Since the system works without a central repository or single administrator, bitcoin is called the first decentralized digital currency. Besides being created as a reward for mining, bitcoin can be exchanged for other currencies, products, and services in legal or black markets."),
("Ripple", 297.39, "Ripple is a real-time gross settlement system (RTGS), currency exchange and remittance network by Ripple. Also called the Ripple Transaction Protocol (RTXP) or Ripple protocol, it is built upon a distributed open source Internet protocol, consensus ledger and native currency called XRP (ripples). Released in 2012, Ripple purports to enable secure, instant and nearly free global financial transactions of any size with no chargebacks. It supports tokens representing fiat currency, cryptocurrency, commodity or any other unit of value such as frequent flier miles or mobile minutes. At its core, Ripple is based around a shared, public database or ledger, which uses a consensus process that allows for payments, exchanges and remittance in a distributed process."),
("Ether", 0.15, "Ethereum is an open-source, public, blockchain-based distributed computing platform featuring smart contract (scripting) functionality. It provides a decentralized Turing-complete virtual machine, the Ethereum Virtual Machine (EVM), which can execute scripts using an international network of public nodes. Ethereum also provides a cryptocurrency token called ether, which can be transferred between accounts and used to compensate participant nodes for computations performed. Gas, an internal transaction pricing mechanism, is used to mitigate spam and allocate resources on the network.");

UPDATE cryptocurrencies SET current = ovalue;

INSERT INTO commodities (name, ovalue, description) VALUES
("Gold", 1285.9, "Gold is a chemical element with symbol Au (from Latin: aurum) and atomic number 79. In its purest form, it is a bright, slightly reddish yellow, dense, soft, malleable, and ductile metal. Chemically, gold is a transition metal and a group 11 element. It is one of the least reactive chemical elements and is solid under standard conditions. Gold often occurs in free elemental (native) form, as nuggets or grains, in rocks, in veins, and in alluvial deposits. It occurs in a solid solution series with the native element silver (as electrum) and also naturally alloyed with copper and palladium. Less commonly, it occurs in minerals as gold compounds, often with tellurium (gold tellurides)."),
-- ("Silver", 17.17, "Silver is a chemical element with symbol Ag (from the Latin argentum, derived from the Greek shiny or white) and atomic number 47. A soft, white, lustrous transition metal, it exhibits the highest electrical conductivity, thermal conductivity, and reflectivity of any metal. The metal is found in the Earth's crust in the pure, free elemental form (native silver), as an alloy with gold and other metals, and in minerals such as argentite and chlorargyrite. Most silver is produced as a byproduct of copper, gold, lead, and zinc refining."),
("Crude Oil", 53.51, "Crude oil is a naturally occurring, unrefined petroleum product composed of hydrocarbon deposits in natural underground pools or reservoirs and remains liquid at atmospheric pressure and temperature. Although it is often called black gold, crude oil has a wide ranging viscosity and can vary in colour to various shades of black and yellow depending on its hydrocarbon composition. Crude oil can be refined to produce usable products such as gasoline, diesel and various forms of petrochemicals.");

UPDATE commodities SET current = ovalue;

INSERT INTO updates (name, current) SELECT name, pclose FROM stocks;

UPDATE updates SET time = '2017-09-25 14:00:00';

INSERT INTO updates (name, current, difference, percentage) SELECT name, ovalue, ovalue - pclose, (((ovalue - pclose) * 100) / pclose) FROM stocks;

INSERT INTO updates (name, current) SELECT name, ovalue FROM cryptocurrencies;

INSERT INTO updates (name, current) SELECT name, ovalue FROM commodities;

UPDATE updates SET time = '2017-09-26 09:00:00' WHERE time IS NULL;

UPDATE users SET balance = 0;